title: Plenert Macdonald Software Services
email: software@apmac.us
author: Aidan Plenert Macdonald
copyright: "Plenert Macdonald Software Services LLC"

defaults:
  home:
    heading: "Plenert Macdonald Software Services"
    subheading: "Data & Cloud Engineering Experts"
    banner: "Your image url"

banner:
  height: 0px
  image: ""

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
